-- =========================================================
-- MEOW MEOW - BƯỚC 2
-- Tracking đầy đủ + quản trị giáo viên + bảng xếp hạng
--
-- Chạy file này SAU file supabase-setup.sql đã chạy trước đó.
-- Có thể chạy lại nhiều lần.
-- =========================================================

-- 1. Nhật ký hoạt động
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course text not null check (course in ('hsk1','hsk4')),
  lesson_no integer not null check (lesson_no > 0),
  activity_type text not null check (
    activity_type in ('lesson_open','game_score','lesson_complete')
  ),
  detail jsonb not null default '{}'::jsonb,
  activity_at timestamptz not null default now()
);

create index if not exists idx_activity_user_time
on public.activity_logs(user_id, activity_at desc);

create index if not exists idx_activity_course_lesson
on public.activity_logs(course, lesson_no, activity_at desc);

alter table public.activity_logs enable row level security;

drop policy if exists "activity_select_own" on public.activity_logs;
create policy "activity_select_own"
on public.activity_logs
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "activity_insert_own" on public.activity_logs;
create policy "activity_insert_own"
on public.activity_logs
for insert
to authenticated
with check ((select auth.uid()) = user_id);


-- 2. Danh sách tài khoản giáo viên/quản trị
create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admin_users_select_own" on public.admin_users;
create policy "admin_users_select_own"
on public.admin_users
for select
to authenticated
using ((select auth.uid()) = id);


-- 3. Hàm kiểm tra quyền quản trị
create schema if not exists private;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users a
    where a.id = (select auth.uid())
  );
$$;

revoke all on function private.is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;


-- 4. Giáo viên được đọc toàn bộ dữ liệu cần cho dashboard
drop policy if exists "profiles_admin_select" on public.profiles;
create policy "profiles_admin_select"
on public.profiles
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "progress_admin_select" on public.lesson_progress;
create policy "progress_admin_select"
on public.lesson_progress
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "games_admin_select" on public.game_results;
create policy "games_admin_select"
on public.game_results
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "activity_admin_select" on public.activity_logs;
create policy "activity_admin_select"
on public.activity_logs
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "admin_users_admin_select" on public.admin_users;
create policy "admin_users_admin_select"
on public.admin_users
for select
to authenticated
using ((select private.is_admin()));


-- 5. Bảng xếp hạng an toàn cho học sinh.
-- Chỉ công khai TÊN HIỂN THỊ + số liệu học tập tổng hợp.
-- Không đưa username, email hay user_id ra view này.
drop view if exists public.course_leaderboard;

create view public.course_leaderboard as
with
pstats as (
  select
    user_id,
    course,
    count(*) filter (where status = 'completed')::int as completed_lessons,
    count(*)::int as touched_lessons,
    round(coalesce(avg(best_score) filter (where best_score is not null),0))::int as avg_best_score,
    max(last_opened_at) as progress_last_active
  from public.lesson_progress
  group by user_id, course
),
gstats as (
  select
    user_id,
    course,
    count(*)::int as game_attempts,
    round(coalesce(avg(score),0))::int as avg_game_score,
    count(*) filter (where played_at >= now() - interval '7 days')::int as attempts_7d,
    count(distinct (played_at at time zone 'UTC')::date)
      filter (where played_at >= now() - interval '7 days')::int as active_days_7d,
    max(played_at) as game_last_active
  from public.game_results
  group by user_id, course
),
all_courses as (
  select user_id, course from pstats
  union
  select user_id, course from gstats
)
select
  pr.display_name,
  ac.course,
  coalesce(ps.completed_lessons,0)::int as completed_lessons,
  coalesce(ps.touched_lessons,0)::int as touched_lessons,
  coalesce(ps.avg_best_score,0)::int as avg_best_score,
  coalesce(gs.game_attempts,0)::int as game_attempts,
  coalesce(gs.avg_game_score,0)::int as avg_game_score,
  coalesce(gs.attempts_7d,0)::int as attempts_7d,
  coalesce(gs.active_days_7d,0)::int as active_days_7d,
  greatest(ps.progress_last_active, gs.game_last_active) as last_active,
  (
    coalesce(ps.completed_lessons,0) * 100
    + coalesce(ps.avg_best_score,0)
    + least(coalesce(gs.game_attempts,0),50)
  )::int as points
from all_courses ac
join public.profiles pr on pr.id = ac.user_id
left join pstats ps on ps.user_id = ac.user_id and ps.course = ac.course
left join gstats gs on gs.user_id = ac.user_id and gs.course = ac.course;

revoke all on public.course_leaderboard from anon;
grant select on public.course_leaderboard to authenticated;
