/* Dữ liệu tổng hợp từ toàn bộ nội dung của 12 PDF. */
const N = "Danh từ / 名词";
const V = "Động từ / 动词";
const A = "Tính từ / 形容词";
const P = "Cụm từ / 短语";
const ADV = "Phó từ / 副词";
const PN = "Địa danh / 地名";
const O = "Từ tượng thanh / 拟声词";
const vocab = (word, pinyin, meaning, partOfSpeech, exampleZh, exampleVi) => ({ word, pinyin, meaning, partOfSpeech, exampleZh, exampleVi });

window.HSK4_TOPICS = [];

window.HSK4_TOPICS.push({
  id: 1,
  title: "Thực vật và các phần mở rộng",
  chineseTitle: "植物",
  description: "Toàn bộ từ vựng trong PDF: thực vật, thời tiết và tình yêu.",
  vocabulary: [
    vocab("松树", "sōngshù", "cây thông, cây tùng", N, "这座山上有很多松树。", "Trên ngọn núi này có rất nhiều cây thông."),
    vocab("竹子", "zhúzi", "cây tre, cây trúc", N, "熊猫最喜欢吃竹子。", "Gấu trúc thích ăn tre nhất."),
    vocab("梅花", "méihuā", "hoa mai", N, "梅花不怕冬天的风雪。", "Hoa mai không sợ gió tuyết mùa đông."),
    vocab("柳树", "liǔshù", "cây liễu", N, "河边有一棵高高的柳树。", "Bên bờ sông có một cây liễu cao."),
    vocab("玫瑰花", "méiguīhuā", "hoa hồng", N, "他送给女朋友一束玫瑰花。", "Anh ấy tặng bạn gái một bó hoa hồng."),
    vocab("兰花", "lánhuā", "hoa lan", N, "这盆兰花开得很漂亮。", "Chậu hoa lan này nở rất đẹp."),
    vocab("菊花", "júhuā", "hoa cúc", N, "菊花常常在秋天开放。", "Hoa cúc thường nở vào mùa thu."),
    vocab("向日葵", "xiàngrìkuí", "hoa hướng dương", N, "向日葵总是朝着太阳生长。", "Hoa hướng dương luôn phát triển hướng về phía mặt trời."),
    vocab("象征", "xiàngzhēng", "tượng trưng", V, "玫瑰花象征着爱情。", "Hoa hồng tượng trưng cho tình yêu."),
    vocab("清香", "qīngxiāng", "hương thơm dịu nhẹ", N, "兰花散发着淡淡的清香。", "Hoa lan tỏa ra hương thơm dịu nhẹ."),
    vocab("开放", "kāifàng", "nở, nở rộ", V, "春天来了，花儿都开放了。", "Mùa xuân đến, hoa đều đã nở."),
    vocab("刮风", "guāfēng", "có gió, gió thổi", V, "今天外面刮大风。", "Hôm nay bên ngoài có gió lớn."),
    vocab("下雨", "xiàyǔ", "mưa", V, "明天可能会下雨。", "Ngày mai có thể trời sẽ mưa."),
    vocab("下雪", "xiàxuě", "tuyết rơi", V, "北京冬天常常下雪。", "Mùa đông ở Bắc Kinh thường có tuyết rơi."),
    vocab("云（多云）", "yún (duōyún)", "mây (nhiều mây)", N, "今天天上有很多云，是多云天气。", "Hôm nay trên trời có nhiều mây, là thời tiết nhiều mây."),
    vocab("下雾", "xiàwù", "có sương mù", V, "早上公路上下雾了。", "Buổi sáng trên đường có sương mù."),
    vocab("太阳", "tàiyáng", "mặt trời", N, "太阳从东方升起来。", "Mặt trời mọc từ phía đông."),
    vocab("月亮", "yuèliang", "mặt trăng", N, "今晚的月亮很亮。", "Mặt trăng tối nay rất sáng."),
    vocab("弯月", "wānyuè", "trăng lưỡi liềm", N, "天上挂着一轮弯月。", "Trên trời treo một vầng trăng lưỡi liềm."),
    vocab("满月", "mǎnyuè", "trăng tròn", N, "十五的月亮是满月。", "Trăng ngày rằm là trăng tròn."),
    vocab("星星", "xīngxing", "ngôi sao", N, "夜空中有很多星星。", "Trên bầu trời đêm có rất nhiều ngôi sao."),
    vocab("情人节", "qíngrénjié", "Lễ Tình nhân", N, "二月十四号是情人节。", "Ngày 14 tháng 2 là Lễ Tình nhân."),
    vocab("心爱的", "xīn'ài de", "yêu dấu, yêu quý", A, "这是我心爱的礼物。", "Đây là món quà yêu quý của tôi."),
    vocab("拿不定主意", "ná bù dìng zhǔyi", "không quyết định được, lưỡng lự", P, "两件衣服都很好看，我拿不定主意。", "Cả hai bộ quần áo đều đẹp nên tôi không quyết định được."),
    vocab("外表", "wàibiǎo", "vẻ ngoài, diện mạo", N, "不要只看一个人的外表。", "Đừng chỉ nhìn vào vẻ ngoài của một người."),
    vocab("迷人", "mírén", "quyến rũ, cuốn hút", A, "她的笑容非常迷人。", "Nụ cười của cô ấy rất cuốn hút."),
    vocab("心眼好", "xīnyǎn hǎo", "tốt bụng", P, "李小姐心眼很好，常常帮助别人。", "Cô Lý rất tốt bụng và thường giúp đỡ người khác."),
    vocab("苗条", "miáotiao", "thon thả, thanh mảnh", A, "她身材很苗条。", "Dáng người cô ấy rất thon thả."),
    vocab("聪明", "cōngming", "thông minh", A, "这个孩子又聪明又努力。", "Đứa trẻ này vừa thông minh vừa chăm chỉ."),
    vocab("究竟", "jiūjìng", "rốt cuộc, thực ra", ADV, "这究竟是怎么回事？", "Rốt cuộc chuyện này là thế nào?")
  ]
});

window.HSK4_TOPICS.push({
  id: 2,
  title: "Cảm xúc và các phần mở rộng",
  chineseTitle: "感情",
  description: "Toàn bộ từ vựng trong PDF: cảm xúc, phòng ngủ và câu chuyện giao tiếp.",
  vocabulary: [
    vocab("高兴", "gāoxìng", "vui, vui mừng", A, "今天见到你，我很高兴。", "Hôm nay gặp bạn, tôi rất vui."),
    vocab("开心", "kāixīn", "vui vẻ", A, "跟朋友聊天让我很开心。", "Trò chuyện với bạn bè khiến tôi rất vui."),
    vocab("难过", "nánguò", "buồn, khó chịu", A, "听到这个消息，她很难过。", "Nghe tin này, cô ấy rất buồn."),
    vocab("哭", "kū", "khóc", V, "那个孩子为什么哭？", "Tại sao đứa trẻ đó khóc?"),
    vocab("大哭", "dàkū", "khóc lớn", V, "他摔倒以后大哭起来。", "Sau khi bị ngã, cậu ấy òa khóc."),
    vocab("伤心", "shāngxīn", "đau lòng, buồn bã", A, "她因为考试没考好而伤心。", "Cô ấy buồn vì làm bài thi không tốt."),
    vocab("发愁", "fāchóu", "lo âu, buồn rầu", V, "他正在为找工作发愁。", "Anh ấy đang lo lắng về việc tìm việc làm."),
    vocab("愤怒", "fènnù", "phẫn nộ, tức giận", A, "听到这件事，他感到非常愤怒。", "Nghe chuyện này, anh ấy cảm thấy vô cùng tức giận."),
    vocab("发火", "fāhuǒ", "nổi giận", V, "请别为这件小事发火。", "Xin đừng nổi giận vì chuyện nhỏ này."),
    vocab("发脾气", "fā píqi", "nổi nóng, cáu giận", P, "他有时候会对家人发脾气。", "Đôi khi anh ấy nổi nóng với người nhà."),
    vocab("微笑", "wēixiào", "mỉm cười", V, "她微笑着向我打招呼。", "Cô ấy mỉm cười chào tôi."),
    vocab("大笑", "dàxiào", "cười lớn", V, "大家听完笑话都大笑起来。", "Mọi người nghe xong câu chuyện cười đều cười lớn."),
    vocab("嫉妒", "jídù", "đố kỵ, ghen tị", V, "不要嫉妒别人的成功。", "Đừng ghen tị với thành công của người khác."),
    vocab("头疼", "tóuténg", "đau đầu", A, "我今天有点儿头疼。", "Hôm nay tôi hơi đau đầu."),
    vocab("恨", "hèn", "căm ghét, hận", V, "我最恨别人说谎。", "Tôi ghét nhất việc người khác nói dối."),
    vocab("床", "chuáng", "giường", N, "卧室里有一张床。", "Trong phòng ngủ có một chiếc giường."),
    vocab("被子", "bèizi", "chăn", N, "天气冷了，请盖好被子。", "Trời lạnh rồi, hãy đắp chăn cho kín."),
    vocab("枕头", "zhěntou", "gối", N, "这个枕头太高了。", "Chiếc gối này quá cao."),
    vocab("床头灯", "chuángtóudēng", "đèn đầu giường", N, "睡觉前请关掉床头灯。", "Trước khi ngủ hãy tắt đèn đầu giường."),
    vocab("闹钟", "nàozhōng", "đồng hồ báo thức", N, "我每天早上被闹钟叫醒。", "Mỗi sáng tôi được đồng hồ báo thức đánh thức."),
    vocab("床头柜", "chuángtóuguì", "tủ đầu giường", N, "手机放在床头柜上。", "Điện thoại được đặt trên tủ đầu giường."),
    vocab("拖鞋", "tuōxié", "dép lê", N, "我在家里常常穿拖鞋。", "Ở nhà tôi thường đi dép lê."),
    vocab("床单", "chuángdān", "ga trải giường", N, "妈妈正在换床单。", "Mẹ đang thay ga trải giường."),
    vocab("床垫", "chuángdiàn", "nệm", N, "这个床垫睡起来很舒服。", "Chiếc nệm này nằm rất thoải mái."),
    vocab("褥子", "rùzi", "đệm lót", N, "奶奶在床上铺了一床褥子。", "Bà trải một tấm đệm lót trên giường."),
    vocab("弹簧", "tánhuáng", "lò xo", N, "这个床垫里面有弹簧。", "Bên trong chiếc nệm này có lò xo."),
    vocab("弹簧床垫", "tánhuáng chuángdiàn", "nệm lò xo", N, "这是一张新的弹簧床垫。", "Đây là một chiếc nệm lò xo mới."),
    vocab("海绵", "hǎimián", "mút, bọt biển", N, "这个垫子是海绵做的。", "Tấm đệm này được làm bằng mút."),
    vocab("海绵床垫", "hǎimián chuángdiàn", "nệm mút", N, "海绵床垫睡起来很软。", "Nệm mút nằm rất mềm."),
    vocab("盖", "gài", "đắp, đậy", V, "晚上睡觉要盖被子。", "Buổi tối khi ngủ phải đắp chăn."),
    vocab("厚", "hòu", "dày", A, "冬天我用一床厚被子。", "Mùa đông tôi dùng một chiếc chăn dày."),
    vocab("母牛", "mǔniú", "bò cái, bò mẹ", N, "农场里有一头母牛。", "Trong trang trại có một con bò cái."),
    vocab("夸", "kuā", "khen ngợi", V, "老师夸他汉语说得好。", "Giáo viên khen cậu ấy nói tiếng Trung tốt."),
    vocab("皮肤", "pífū", "da", N, "这个孩子的皮肤很白。", "Da của đứa trẻ này rất trắng."),
    vocab("含", "hán", "ngậm, chứa", V, "小孩儿嘴里含着奶嘴。", "Đứa trẻ đang ngậm núm vú giả trong miệng."),
    vocab("奶嘴", "nǎizuǐ", "núm vú giả", N, "宝宝嘴里的奶嘴掉了。", "Núm vú giả trong miệng em bé rơi xuống."),
    vocab("小天使", "xiǎo tiānshǐ", "thiên thần nhỏ", N, "这个可爱的孩子像个小天使。", "Đứa trẻ đáng yêu này giống như một thiên thần nhỏ."),
    vocab("喂养", "wèiyǎng", "nuôi dưỡng, cho ăn", V, "这些小动物由工作人员喂养。", "Những con vật nhỏ này được nhân viên nuôi dưỡng."),
    vocab("吓", "xià", "làm sợ, dọa", V, "突然的声音吓了我一跳。", "Âm thanh đột ngột làm tôi giật mình."),
    vocab("尿", "niào", "đi tiểu, nước tiểu", V, "小孩子想尿尿。", "Đứa trẻ muốn đi tiểu."),
    vocab("吓出尿", "xià chū niào", "sợ đến tè ra quần", P, "孩子被突然的声音吓出了尿。", "Đứa trẻ bị âm thanh đột ngột dọa đến tè ra quần.")
  ]
});

window.HSK4_TOPICS.push({
  id: 3,
  title: "Đồ dùng cá nhân và các phần mở rộng",
  chineseTitle: "个人用品",
  description: "Toàn bộ từ vựng trong PDF: đồ dùng cá nhân, thuốc lá và câu chuyện liên quan.",
  vocabulary: [
    vocab("T恤", "T xù", "áo thun", N, "夏天我喜欢穿白色的T恤。", "Mùa hè tôi thích mặc áo thun trắng."),
    vocab("牛仔裤", "niúzǎikù", "quần bò, quần jean", N, "这条牛仔裤很适合你。", "Chiếc quần jean này rất hợp với bạn."),
    vocab("手表", "shǒubiǎo", "đồng hồ đeo tay", N, "我的手表慢了五分钟。", "Đồng hồ đeo tay của tôi chậm năm phút."),
    vocab("钟", "zhōng", "đồng hồ", N, "墙上的钟已经八点了。", "Đồng hồ trên tường đã chỉ tám giờ."),
    vocab("电话", "diànhuà", "điện thoại, cuộc gọi", N, "我晚一点儿给你打电话。", "Lát nữa tôi sẽ gọi điện cho bạn."),
    vocab("手机", "shǒujī", "điện thoại di động", N, "上课的时候请关掉手机。", "Khi vào học, vui lòng tắt điện thoại."),
    vocab("火柴", "huǒchái", "diêm, que diêm", N, "他用一根火柴点燃了蜡烛。", "Anh ấy dùng một que diêm để thắp nến."),
    vocab("打火机", "dǎhuǒjī", "bật lửa", N, "这个打火机是谁的？", "Chiếc bật lửa này là của ai?"),
    vocab("香烟", "xiāngyān", "thuốc lá, điếu thuốc", N, "商店里不向未成年人出售香烟。", "Cửa hàng không bán thuốc lá cho người chưa thành niên."),
    vocab("烟头", "yāntóu", "mẩu thuốc lá", N, "请不要把烟头扔在地上。", "Xin đừng vứt mẩu thuốc lá xuống đất."),
    vocab("烟斗", "yāndǒu", "tẩu thuốc", N, "爷爷以前有一个旧烟斗。", "Trước đây ông có một chiếc tẩu thuốc cũ."),
    vocab("烟嘴", "yānzuǐ", "đầu ngậm thuốc", N, "这个烟嘴是木头做的。", "Đầu ngậm thuốc này được làm bằng gỗ."),
    vocab("烟缸", "yāngāng", "gạt tàn thuốc", N, "房间里没有烟缸。", "Trong phòng không có gạt tàn thuốc."),
    vocab("烟囱", "yāncōng", "ống khói", N, "烟囱里冒出了黑烟。", "Khói đen bốc ra từ ống khói."),
    vocab("发明", "fāmíng", "phát minh", V, "爱迪生发明了很多东西。", "Edison đã phát minh ra nhiều thứ."),
    vocab("烟草", "yāncǎo", "thuốc lá, cây thuốc lá", N, "烟草对身体健康有害。", "Thuốc lá có hại cho sức khỏe."),
    vocab("冒烟", "màoyān", "bốc khói", V, "厨房里的锅正在冒烟。", "Chiếc nồi trong bếp đang bốc khói."),
    vocab("烟瘾", "yānyǐn", "nghiện thuốc lá", N, "他的烟瘾很大，一天抽很多烟。", "Ông ấy nghiện thuốc nặng và hút rất nhiều thuốc mỗi ngày."),
    vocab("劝", "quàn", "khuyên nhủ", V, "家人劝他早点儿戒烟。", "Gia đình khuyên ông ấy sớm cai thuốc."),
    vocab("烟灰", "yānhuī", "tàn thuốc", N, "茶几上落了很多烟灰。", "Trên bàn trà rơi rất nhiều tàn thuốc."),
    vocab("乌烟瘴气", "wūyānzhàngqì", "ô nhiễm, hỗn loạn, ngột ngạt", P, "屋子里乌烟瘴气，让人很不舒服。", "Trong phòng khói bụi ngột ngạt khiến người ta rất khó chịu."),
    vocab("烟鬼", "yānguǐ", "người nghiện thuốc lá", N, "他以前是个烟鬼，现在已经戒烟了。", "Trước đây ông ấy nghiện thuốc, nhưng giờ đã cai rồi."),
    vocab("害", "hài", "làm hại, gây hại", V, "抽烟不仅害自己，也害别人。", "Hút thuốc không chỉ hại bản thân mà còn hại người khác."),
    vocab("夺", "duó", "giật, cướp, đoạt", V, "她把丈夫手里的烟夺了过来。", "Cô ấy giật điếu thuốc khỏi tay chồng."),
    vocab("茶几", "chájī", "bàn trà", N, "茶几上放着一杯茶。", "Trên bàn trà có đặt một cốc trà."),
    vocab("顶", "dǐng", "đỉnh, chóp", N, "他快要爬到烟囱顶了。", "Ông ấy sắp trèo tới đỉnh ống khói."),
    vocab("心疼", "xīnténg", "đau lòng, xót xa, thương", V, "妈妈很心疼生病的孩子。", "Người mẹ rất xót xa cho đứa con bị bệnh.")
  ]
});

window.HSK4_TOPICS.push({
  id: 4,
  title: "Nghề nghiệp và các phần mở rộng",
  chineseTitle: "职业",
  description: "Toàn bộ từ vựng trong PDF: nghề nghiệp, gia đình và câu chuyện ảnh gia đình.",
  vocabulary: [
    vocab("大夫", "dàifu", "bác sĩ", N, "王大夫正在给病人看病。", "Bác sĩ Vương đang khám bệnh cho bệnh nhân."),
    vocab("工人", "gōngrén", "công nhân", N, "这些工人在工厂里工作。", "Những công nhân này làm việc trong nhà máy."),
    vocab("农民", "nóngmín", "nông dân", N, "农民们正在田里干活儿。", "Những người nông dân đang làm việc ngoài đồng."),
    vocab("护士", "hùshi", "y tá", N, "护士每天都认真照顾病人。", "Y tá chăm sóc bệnh nhân chu đáo mỗi ngày."),
    vocab("邮递员", "yóudìyuán", "người đưa thư", N, "邮递员把信送到了我家。", "Người đưa thư đã mang thư đến nhà tôi."),
    vocab("售货员", "shòuhuòyuán", "nhân viên bán hàng", N, "售货员热情地回答了我的问题。", "Nhân viên bán hàng nhiệt tình trả lời câu hỏi của tôi."),
    vocab("警察", "jǐngchá", "cảnh sát", N, "有困难的时候可以找警察。", "Khi gặp khó khăn có thể tìm cảnh sát."),
    vocab("军人", "jūnrén", "quân nhân", N, "他的哥哥是一名军人。", "Anh trai của anh ấy là một quân nhân."),
    vocab("司机", "sījī", "tài xế", N, "这位司机开车很小心。", "Người tài xế này lái xe rất cẩn thận."),
    vocab("厨师", "chúshī", "đầu bếp", N, "这家饭店的厨师做菜很好吃。", "Đầu bếp của nhà hàng này nấu ăn rất ngon."),
    vocab("理发员", "lǐfàyuán", "thợ cắt tóc", N, "理发员正在给客人剪头发。", "Thợ cắt tóc đang cắt tóc cho khách."),
    vocab("牙医", "yáyī", "nha sĩ", N, "我明天要去看牙医。", "Ngày mai tôi phải đi gặp nha sĩ."),
    vocab("画家", "huàjiā", "họa sĩ", N, "那位画家画了很多美丽的风景。", "Vị họa sĩ đó đã vẽ rất nhiều phong cảnh đẹp."),
    vocab("书法家", "shūfǎjiā", "nhà thư pháp", N, "这位书法家的字很有名。", "Chữ của nhà thư pháp này rất nổi tiếng."),
    vocab("歌唱家", "gēchàngjiā", "ca sĩ, nhà thanh nhạc", N, "她是一位著名的歌唱家。", "Cô ấy là một ca sĩ nổi tiếng."),
    vocab("舞蹈家", "wǔdǎojiā", "vũ công, nghệ sĩ múa", N, "那位舞蹈家的表演非常精彩。", "Màn biểu diễn của nghệ sĩ múa đó vô cùng đặc sắc."),
    vocab("职责", "zhízé", "chức trách, trách nhiệm", N, "保护人民是警察的职责。", "Bảo vệ nhân dân là trách nhiệm của cảnh sát."),
    vocab("打交道", "dǎ jiāodào", "tiếp xúc, giao thiệp", P, "我的工作需要经常跟客户打交道。", "Công việc của tôi cần thường xuyên tiếp xúc với khách hàng."),
    vocab("著名", "zhùmíng", "nổi tiếng", A, "他是一位著名的画家。", "Ông ấy là một họa sĩ nổi tiếng."),
    vocab("欣赏", "xīnshǎng", "thưởng thức, ngưỡng mộ", V, "我很欣赏她的舞蹈表演。", "Tôi rất thích màn biểu diễn múa của cô ấy."),
    vocab("退休", "tuìxiū", "nghỉ hưu", V, "爷爷已经退休多年了。", "Ông đã nghỉ hưu nhiều năm rồi."),
    vocab("家庭妇女", "jiātíng fùnǚ", "người nội trợ", N, "我妈妈以前是一位家庭妇女。", "Trước đây mẹ tôi là một người nội trợ."),
    vocab("姑姑", "gūgu", "cô, em/chị gái của bố", N, "我经常去姑姑家玩儿。", "Tôi thường đến nhà cô chơi."),
    vocab("乐呵呵", "lèhēhē", "vui vẻ, hớn hở", A, "爷爷乐呵呵地走进了房间。", "Ông vui vẻ bước vào phòng."),
    vocab("摄影记者", "shèyǐng jìzhě", "phóng viên ảnh", N, "他是一家杂志的摄影记者。", "Anh ấy là phóng viên ảnh của một tạp chí."),
    vocab("嫂子", "sǎozi", "chị dâu", N, "嫂子在医院当护士。", "Chị dâu làm y tá ở bệnh viện."),
    vocab("追", "zhuī", "theo đuổi, tán tỉnh", V, "他追了她五年，两人才结婚。", "Anh ấy theo đuổi cô ấy năm năm rồi hai người mới kết hôn."),
    vocab("玫瑰花", "méiguīhuā", "hoa hồng", N, "有很多人送她玫瑰花。", "Có rất nhiều người tặng cô ấy hoa hồng."),
    vocab("淘气", "táoqì", "nghịch ngợm", A, "小明是个淘气的孩子。", "Tiểu Minh là một đứa trẻ nghịch ngợm."),
    vocab("脏兮兮", "zāngxīxī", "bẩn thỉu, nhếch nhác", A, "他踢完球以后脸上脏兮兮的。", "Sau khi đá bóng, mặt cậu ấy bẩn thỉu."),
    vocab("乱哄哄", "luànhōnghōng", "lộn xộn, ồn ào", A, "教室里乱哄哄的。", "Trong lớp học rất ồn ào lộn xộn."),
    vocab("坏毛病", "huài máobìng", "tật xấu", N, "他正在努力改掉坏毛病。", "Cậu ấy đang cố gắng sửa bỏ tật xấu."),
    vocab("挨骂", "áimà", "bị mắng", V, "他小时候没少挨爷爷的骂。", "Khi còn nhỏ cậu ấy thường bị ông mắng."),
    vocab("支持", "zhīchí", "ủng hộ", V, "妈妈一直支持我的决定。", "Mẹ luôn ủng hộ quyết định của tôi."),
    vocab("明星", "míngxīng", "ngôi sao, minh tinh", N, "那位明星很受年轻人欢迎。", "Ngôi sao đó rất được giới trẻ yêu thích."),
    vocab("全家福", "quánjiāfú", "ảnh gia đình", N, "我们春节拍了一张全家福。", "Dịp Tết chúng tôi chụp một bức ảnh gia đình."),
    vocab("合家欢", "héjiāhuān", "ảnh sum họp gia đình", N, "中国人也把这种照片叫合家欢。", "Người Trung Quốc cũng gọi kiểu ảnh này là ảnh sum họp gia đình."),
    vocab("职业", "zhíyè", "nghề nghiệp", N, "我的职业是医生。", "Nghề nghiệp của tôi là bác sĩ.")
  ]
});

window.HSK4_TOPICS.push({
  id: 5,
  title: "Mũ, giày và câu chuyện lễ phép",
  chineseTitle: "礼帽",
  description: "Toàn bộ từ vựng trong PDF: các loại mũ, giày dép và câu chuyện bán mũ.",
  vocabulary: [
    vocab("礼帽", "lǐmào", "mũ lễ, mũ chóp", N, "这位先生戴着一顶黑色礼帽。", "Vị tiên sinh này đội một chiếc mũ lễ màu đen."),
    vocab("鸭舌帽", "yāshémào", "mũ lưỡi trai", N, "运动的时候我喜欢戴鸭舌帽。", "Khi vận động tôi thích đội mũ lưỡi trai."),
    vocab("草帽", "cǎomào", "mũ rơm", N, "农民在田里戴着草帽。", "Người nông dân đội mũ rơm ngoài đồng."),
    vocab("便帽", "biànmào", "mũ thường, mũ mềm", N, "这顶便帽戴起来很舒服。", "Chiếc mũ thường này đội rất thoải mái."),
    vocab("皮帽", "pímào", "mũ da, mũ lông", N, "天气很冷，他戴上了皮帽。", "Trời rất lạnh nên anh ấy đội mũ da."),
    vocab("毛线帽", "máoxiànmào", "mũ len", N, "冬天戴毛线帽很暖和。", "Mùa đông đội mũ len rất ấm."),
    vocab("贝雷帽", "bèiléimào", "mũ nồi", N, "她戴着一顶红色贝雷帽。", "Cô ấy đội một chiếc mũ nồi màu đỏ."),
    vocab("瓜皮帽", "guāpímào", "mũ quả dưa", N, "这种瓜皮帽现在很少见。", "Loại mũ quả dưa này hiện nay rất ít gặp."),
    vocab("皮鞋", "píxié", "giày da", N, "上班时他常常穿黑皮鞋。", "Khi đi làm anh ấy thường mang giày da đen."),
    vocab("布鞋", "bùxié", "giày vải", N, "这双布鞋又轻又舒服。", "Đôi giày vải này vừa nhẹ vừa thoải mái."),
    vocab("高跟鞋", "gāogēnxié", "giày cao gót", N, "她今天穿了一双高跟鞋。", "Hôm nay cô ấy mang một đôi giày cao gót."),
    vocab("靴子", "xuēzi", "ủng, bốt", N, "下雪的时候要穿靴子。", "Khi trời tuyết phải mang ủng."),
    vocab("拖鞋", "tuōxié", "dép lê", N, "进屋以后请换上拖鞋。", "Sau khi vào nhà hãy thay dép lê."),
    vocab("旅游鞋", "lǚyóuxié", "giày thể thao, giày du lịch", N, "出去旅行要穿舒服的旅游鞋。", "Đi du lịch nên mang giày thể thao thoải mái."),
    vocab("冰鞋", "bīngxié", "giày trượt băng", N, "滑冰以前要穿好冰鞋。", "Trước khi trượt băng phải mang giày trượt cho chắc."),
    vocab("旱冰鞋", "hànbīngxié", "giày patin", N, "孩子们穿着旱冰鞋在公园里玩儿。", "Bọn trẻ mang giày patin chơi trong công viên."),
    vocab("摆", "bǎi", "xếp đặt, bày biện", V, "小伙子把帽子摆在地摊上。", "Chàng trai bày những chiếc mũ trên quầy hàng vỉa hè."),
    vocab("地毯", "dìtǎn", "thảm trải sàn", N, "客厅里铺着一张地毯。", "Trong phòng khách trải một tấm thảm."),
    vocab("地摊", "dìtān", "sạp hàng vỉa hè", N, "他在街边摆了一个地摊。", "Anh ấy bày một sạp hàng bên đường."),
    vocab("种类", "zhǒnglèi", "chủng loại", N, "这里的帽子种类很多。", "Mũ ở đây có rất nhiều chủng loại."),
    vocab("卖力", "màilì", "gắng sức, hết mình", A, "他在街上卖力地吆喝。", "Anh ấy cố hết sức rao hàng trên phố."),
    vocab("吸引", "xīyǐn", "thu hút, hấp dẫn", V, "漂亮的帽子吸引了很多顾客。", "Những chiếc mũ đẹp thu hút nhiều khách hàng."),
    vocab("保护", "bǎohù", "bảo vệ", V, "帽子可以保护我们的头。", "Mũ có thể bảo vệ đầu của chúng ta."),
    vocab("秃头", "tūtóu", "đầu hói, người hói đầu", N, "老人想买帽子保护他的秃头。", "Ông lão muốn mua mũ để bảo vệ đầu hói của mình."),
    vocab("礼貌", "lǐmào", "lễ phép, lịch sự", N, "跟老人说话要有礼貌。", "Nói chuyện với người lớn tuổi phải lịch sự."),
    vocab("转身", "zhuǎnshēn", "quay người", V, "老人听完以后转身就走。", "Ông lão nghe xong liền quay người bỏ đi."),
    vocab("急", "jí", "gấp, vội, sốt ruột", A, "小伙子一看老人要走就急了。", "Thấy ông lão sắp đi, chàng trai liền sốt ruột.")
  ]
});

window.HSK4_TOPICS.push({
  id: 6,
  title: "Thể thao, động tác và bóng đá",
  chineseTitle: "运动",
  description: "Toàn bộ từ vựng trong PDF: các môn thể thao, động tác và câu chuyện bóng đá.",
  vocabulary: [
    vocab("乒乓球", "pīngpāngqiú", "bóng bàn", N, "我每个周末都打乒乓球。", "Cuối tuần nào tôi cũng chơi bóng bàn."),
    vocab("羽毛球", "yǔmáoqiú", "cầu lông", N, "姐姐很喜欢打羽毛球。", "Chị gái rất thích chơi cầu lông."),
    vocab("网球", "wǎngqiú", "quần vợt", N, "他对打网球很感兴趣。", "Anh ấy rất hứng thú với việc chơi quần vợt."),
    vocab("足球", "zúqiú", "bóng đá, quả bóng đá", N, "孩子们正在操场上踢足球。", "Bọn trẻ đang đá bóng trên sân vận động."),
    vocab("篮球", "lánqiú", "bóng rổ", N, "我们下午一起打篮球吧。", "Chiều nay chúng ta cùng chơi bóng rổ nhé."),
    vocab("排球", "páiqiú", "bóng chuyền", N, "学校有一支女子排球队。", "Trường có một đội bóng chuyền nữ."),
    vocab("台球", "táiqiú", "bi-a", N, "他下班以后常去打台球。", "Sau giờ làm anh ấy thường đi chơi bi-a."),
    vocab("高尔夫球", "gāo'ěrfūqiú", "gôn", N, "我还不会打高尔夫球。", "Tôi vẫn chưa biết chơi gôn."),
    vocab("规则", "guīzé", "quy tắc, luật lệ", N, "比赛以前要先了解规则。", "Trước khi thi đấu phải hiểu rõ luật chơi."),
    vocab("裁判员", "cáipànyuán", "trọng tài", N, "裁判员吹响了比赛结束的哨子。", "Trọng tài thổi còi kết thúc trận đấu."),
    vocab("球迷", "qiúmí", "người hâm mộ bóng đá", N, "很多球迷来到现场看比赛。", "Rất nhiều người hâm mộ đến sân xem trận đấu."),
    vocab("犯规", "fànguī", "phạm luật", V, "那名球员因为犯规被罚了。", "Cầu thủ đó bị phạt vì phạm luật."),
    vocab("倒", "dào", "rót, đổ", V, "请给客人倒一杯茶。", "Hãy rót cho khách một cốc trà."),
    vocab("倒茶", "dào chá", "rót trà", P, "客人来了，请给他们倒茶。", "Khách đến rồi, hãy rót trà cho họ."),
    vocab("倒", "dǎo", "ngã, đổ", V, "风太大了，树倒了。", "Gió quá lớn nên cây đã đổ."),
    vocab("摔倒", "shuāidǎo", "té ngã", V, "他跑步时不小心摔倒了。", "Anh ấy vô ý bị ngã khi chạy bộ."),
    vocab("飞", "fēi", "bay", V, "一只鞋向守门员飞了过去。", "Một chiếc giày bay về phía thủ môn."),
    vocab("举", "jǔ", "giơ, nâng", V, "孩子们举手回答问题。", "Bọn trẻ giơ tay trả lời câu hỏi."),
    vocab("砍", "kǎn", "chặt", V, "工人把那棵枯树砍倒了。", "Công nhân đã chặt đổ cây khô đó."),
    vocab("磕", "kē", "va, đập vào", V, "他跑得太快，头磕到门上了。", "Anh ấy chạy quá nhanh nên đầu va vào cửa."),
    vocab("撞", "zhuàng", "đâm, va vào", V, "两辆车撞在一起了。", "Hai chiếc xe đã đâm vào nhau."),
    vocab("滚", "gǔn", "lăn", V, "足球慢慢地滚进了球门。", "Quả bóng từ từ lăn vào khung thành."),
    vocab("射门", "shèmén", "sút bóng vào khung thành", V, "麦克正在练习射门。", "Mike đang luyện sút bóng."),
    vocab("守门员", "shǒuményuán", "thủ môn", N, "玛丽站在球门前当守门员。", "Mary đứng trước khung thành làm thủ môn."),
    vocab("三分之一", "sānfēnzhīyī", "một phần ba", P, "三分之一的学生表示同意。", "Một phần ba số học sinh bày tỏ sự đồng ý."),
    vocab("挡", "dǎng", "chặn, che", V, "她站在门前挡住了足球。", "Cô ấy đứng trước cửa chặn quả bóng."),
    vocab("张开胳膊", "zhāngkāi gēbo", "dang rộng cánh tay", P, "守门员张开胳膊准备接球。", "Thủ môn dang rộng cánh tay chuẩn bị bắt bóng."),
    vocab("紧张", "jǐnzhāng", "căng thẳng, hồi hộp", A, "第一次参加比赛，她有点儿紧张。", "Lần đầu tham gia thi đấu, cô ấy hơi hồi hộp."),
    vocab("松", "sōng", "lỏng", A, "你的鞋带松了，快系好。", "Dây giày của bạn bị lỏng rồi, mau buộc lại đi."),
    vocab("鞋带", "xiédài", "dây giày", N, "他低下头系鞋带。", "Anh ấy cúi đầu buộc dây giày."),
    vocab("鞋", "xié", "giày", N, "麦克的一只鞋飞了出去。", "Một chiếc giày của Mike bay ra ngoài.")
  ]
});

window.HSK4_TOPICS.push({
  id: 7,
  title: "Khám phá thế giới và đồ dùng",
  chineseTitle: "探索世界",
  description: "Toàn bộ từ vựng trong PDF: đồ dùng, dụng cụ vệ sinh và câu chuyện câu cá.",
  vocabulary: [
    vocab("凉鞋", "liángxié", "dép xăng-đan", N, "夏天穿凉鞋比较舒服。", "Mùa hè mang dép xăng-đan khá thoải mái."),
    vocab("手套", "shǒutào", "găng tay", N, "天气冷了，出门要戴手套。", "Trời lạnh rồi, ra ngoài phải đeo găng tay."),
    vocab("雨衣", "yǔyī", "áo mưa", N, "下雨的时候他穿着雨衣。", "Khi trời mưa anh ấy mặc áo mưa."),
    vocab("伞", "sǎn", "ô, dù", N, "外面下雨了，别忘了带伞。", "Bên ngoài đang mưa, đừng quên mang ô."),
    vocab("眼镜", "yǎnjìng", "kính mắt", N, "我不戴眼镜就看不清楚。", "Tôi không đeo kính thì nhìn không rõ."),
    vocab("墨镜", "mòjìng", "kính râm", N, "太阳很大，他戴上了墨镜。", "Nắng rất to nên anh ấy đeo kính râm."),
    vocab("望远镜", "wàngyuǎnjìng", "ống nhòm, kính viễn vọng", N, "我们用望远镜看远处的鸟。", "Chúng tôi dùng ống nhòm để ngắm những con chim ở xa."),
    vocab("放大镜", "fàngdàjìng", "kính lúp", N, "爷爷用放大镜看小字。", "Ông dùng kính lúp để đọc chữ nhỏ."),
    vocab("脸盆", "liǎnpén", "chậu rửa mặt", N, "脸盆里装满了水。", "Chậu rửa mặt đã đầy nước."),
    vocab("水桶", "shuǐtǒng", "xô nước", N, "他提着一只水桶去打水。", "Anh ấy xách một chiếc xô đi lấy nước."),
    vocab("水龙头", "shuǐlóngtóu", "vòi nước", N, "用完水以后请关上水龙头。", "Dùng nước xong hãy khóa vòi nước."),
    vocab("拖把", "tuōbǎ", "cây lau nhà", N, "妈妈用拖把拖地。", "Mẹ dùng cây lau nhà để lau sàn."),
    vocab("笤帚", "tiáozhou", "chổi", N, "他拿笤帚把地扫干净。", "Anh ấy dùng chổi quét sàn sạch sẽ."),
    vocab("簸箕", "bòji", "hót rác", N, "请把垃圾扫进簸箕里。", "Hãy quét rác vào hót rác."),
    vocab("掸子", "dǎnzi", "chổi phủi bụi", N, "她用掸子清理桌上的灰尘。", "Cô ấy dùng chổi phủi bụi để làm sạch bụi trên bàn."),
    vocab("刷子", "shuāzi", "bàn chải, cọ", N, "我用刷子刷鞋。", "Tôi dùng bàn chải để chải giày."),
    vocab("垃圾", "lājī", "rác", N, "请把垃圾扔进垃圾桶。", "Hãy vứt rác vào thùng rác."),
    vocab("尘土", "chéntǔ", "bụi đất", N, "窗台上有很多尘土。", "Trên bệ cửa sổ có rất nhiều bụi."),
    vocab("用处", "yòngchu", "tác dụng, công dụng", N, "这个工具有什么用处？", "Dụng cụ này có công dụng gì?"),
    vocab("普遍", "pǔbiàn", "phổ biến", A, "钓鱼是一种很普遍的爱好。", "Câu cá là một sở thích rất phổ biến."),
    vocab("唯一", "wéiyī", "duy nhất", A, "这不是他们唯一的不同。", "Đây không phải điểm khác biệt duy nhất của họ."),
    vocab("鱼竿", "yúgān", "cần câu", N, "他手里拿着一根鱼竿。", "Anh ấy cầm một chiếc cần câu trong tay."),
    vocab("鱼钩", "yúgōu", "lưỡi câu", N, "鱼钩已经放进河里了。", "Lưỡi câu đã được thả xuống sông."),
    vocab("上钩", "shànggōu", "cắn câu, mắc câu", V, "他静静地等着鱼儿上钩。", "Anh ấy lặng lẽ chờ cá cắn câu."),
    vocab("耐心", "nàixīn", "kiên nhẫn", N, "钓鱼需要技术和耐心。", "Câu cá cần kỹ thuật và sự kiên nhẫn."),
    vocab("轻松愉快", "qīngsōng yúkuài", "thoải mái, vui vẻ", A, "大家度过了一个轻松愉快的周末。", "Mọi người đã trải qua một cuối tuần thoải mái vui vẻ."),
    vocab("警惕", "jǐngtì", "cảnh giác", V, "我们要警惕那些不诚实的人。", "Chúng ta phải cảnh giác với những người không trung thực.")
  ]
});

window.HSK4_TOPICS.push({
  id: 8,
  title: "Động tác và giao tiếp theo hoàn cảnh",
  chineseTitle: "这是什么动作？",
  description: "Toàn bộ từ vựng trong PDF: động tác, cách mang đồ và câu chuyện chào hỏi.",
  vocabulary: [
    vocab("招", "zhāo", "vẫy, gọi", V, "他站在门口向我招手。", "Anh ấy đứng ở cửa vẫy tay gọi tôi."),
    vocab("摆", "bǎi", "lắc, khoát", V, "他摆摆手说不用谢。", "Anh ấy khoát tay và nói không cần cảm ơn."),
    vocab("挠", "náo", "gãi", V, "他想不起来，只好挠了挠头。", "Anh ấy không nhớ ra nên đành gãi đầu."),
    vocab("抹", "mò", "trát, trét", V, "工人正在给墙抹灰。", "Công nhân đang trát vữa lên tường."),
    vocab("捡", "jiǎn", "nhặt, lượm", V, "请把地上的垃圾捡起来。", "Hãy nhặt rác trên mặt đất lên."),
    vocab("投", "tóu", "ném, quăng", V, "运动员把球投进了篮筐。", "Vận động viên ném bóng vào rổ."),
    vocab("扫", "sǎo", "quét", V, "清洁工每天早上扫马路。", "Công nhân vệ sinh quét đường mỗi sáng."),
    vocab("敲", "qiāo", "gõ", V, "进办公室以前请先敲门。", "Trước khi vào văn phòng hãy gõ cửa."),
    vocab("挑", "tiāo", "gánh, quẩy", V, "农民用扁担挑着两桶水。", "Người nông dân dùng đòn gánh gánh hai thùng nước."),
    vocab("抬", "tái", "nâng, khiêng", V, "两个人一起把桌子抬起来。", "Hai người cùng nâng chiếc bàn lên."),
    vocab("扛", "káng", "vác trên vai", V, "工人肩上扛着一袋米。", "Công nhân vác một bao gạo trên vai."),
    vocab("背", "bēi", "cõng, đeo trên lưng", V, "爸爸背着孩子回家。", "Người bố cõng đứa trẻ về nhà."),
    vocab("搬", "bān", "chuyển, bê, dọn", V, "我们正在搬家具。", "Chúng tôi đang chuyển đồ nội thất."),
    vocab("挎", "kuà", "xách, khoác trên tay", V, "她胳膊上挎着一个包。", "Cô ấy khoác một chiếc túi trên tay."),
    vocab("挂", "guà", "treo, móc", V, "墙上挂着一张地图。", "Trên tường treo một tấm bản đồ."),
    vocab("搂", "lǒu", "ôm, choàng tay", V, "妈妈搂着孩子讲故事。", "Người mẹ ôm đứa trẻ kể chuyện."),
    vocab("和尚", "héshang", "nhà sư", N, "那个和尚挑着水上山。", "Nhà sư đó gánh nước lên núi."),
    vocab("扁担", "biǎndan", "đòn gánh", N, "他用扁担挑水。", "Anh ấy dùng đòn gánh gánh nước."),
    vocab("水桶", "shuǐtǒng", "xô, thùng nước", N, "水桶里装着清水。", "Trong thùng có nước sạch."),
    vocab("随便", "suíbiàn", "tùy tiện, tùy ý", ADV, "在正式场合不能随便说话。", "Trong hoàn cảnh trang trọng không thể nói năng tùy tiện."),
    vocab("方式", "fāngshì", "cách thức, phương thức", N, "这是中国人打招呼的一种方式。", "Đây là một cách chào hỏi của người Trung Quốc."),
    vocab("原来", "yuánlái", "hóa ra, thì ra", ADV, "原来问“吃了吗”也是一种问候。", "Hóa ra hỏi “Ăn chưa?” cũng là một cách chào hỏi."),
    vocab("友好", "yǒuhǎo", "thân thiện, hữu nghị", A, "他想用友好的方式跟老人打招呼。", "Anh ấy muốn chào ông lão một cách thân thiện."),
    vocab("对象", "duìxiàng", "đối tượng", N, "说话时要注意说话的对象。", "Khi nói chuyện phải chú ý đến đối tượng giao tiếp."),
    vocab("场合", "chǎnghé", "hoàn cảnh, trường hợp", N, "不同的场合要用不同的表达。", "Trong những hoàn cảnh khác nhau phải dùng cách diễn đạt khác nhau.")
  ]
});

window.HSK4_TOPICS.push({
  id: 9,
  title: "Trái cây, rau củ và thực phẩm",
  chineseTitle: "水果、蔬菜与肉类",
  description: "Toàn bộ từ vựng trong PDF: rau củ, thực phẩm, địa danh và câu chuyện nấu ăn.",
  vocabulary: [
    vocab("萝卜", "luóbo", "củ cải", N, "冬天的萝卜又甜又脆。", "Củ cải mùa đông vừa ngọt vừa giòn."),
    vocab("胡萝卜", "húluóbo", "cà rốt", N, "兔子喜欢吃胡萝卜。", "Thỏ thích ăn cà rốt."),
    vocab("大葱", "dàcōng", "hành lá", N, "做这道菜要放一点儿大葱。", "Làm món này cần cho một ít hành lá."),
    vocab("大白菜", "dàbáicài", "cải thảo", N, "北方人冬天常吃大白菜。", "Người miền Bắc thường ăn cải thảo vào mùa đông."),
    vocab("圆白菜", "yuánbáicài", "bắp cải", N, "我买了一个圆白菜。", "Tôi đã mua một bắp cải."),
    vocab("冬瓜", "dōngguā", "bí đao", N, "妈妈煮了一锅冬瓜汤。", "Mẹ đã nấu một nồi canh bí đao."),
    vocab("大蒜", "dàsuàn", "tỏi", N, "炒菜时放一点儿大蒜会更香。", "Khi xào rau cho một ít tỏi sẽ thơm hơn."),
    vocab("菠菜", "bōcài", "rau chân vịt", N, "菠菜含有丰富的营养。", "Rau chân vịt chứa nhiều chất dinh dưỡng."),
    vocab("黄瓜", "huángguā", "dưa chuột", N, "夏天吃凉拌黄瓜很清爽。", "Mùa hè ăn dưa chuột trộn rất mát."),
    vocab("茄子", "qiézi", "cà tím", N, "今天晚饭有红烧茄子。", "Bữa tối hôm nay có món cà tím kho."),
    vocab("青椒", "qīngjiāo", "ớt xanh, ớt chuông", N, "这道菜里有青椒和牛肉。", "Trong món này có ớt xanh và thịt bò."),
    vocab("西红柿", "xīhóngshì", "cà chua", N, "我喜欢吃西红柿炒鸡蛋。", "Tôi thích ăn cà chua xào trứng."),
    vocab("豆角", "dòujiǎo", "đậu que", N, "豆角一定要炒熟再吃。", "Đậu que nhất định phải xào chín rồi mới ăn."),
    vocab("菜场", "càichǎng", "chợ rau, chợ thực phẩm", N, "奶奶每天早上去菜场买菜。", "Bà mỗi sáng đều đi chợ mua thức ăn."),
    vocab("凉拌", "liángbàn", "trộn nguội, làm gỏi", V, "这种蔬菜可以凉拌着吃。", "Loại rau này có thể trộn nguội để ăn."),
    vocab("鱼", "yú", "cá", N, "晚饭我们吃了一条鱼。", "Bữa tối chúng tôi ăn một con cá."),
    vocab("鸡", "jī", "gà", N, "院子里有几只鸡。", "Trong sân có vài con gà."),
    vocab("鸡蛋", "jīdàn", "trứng gà", N, "我每天早上吃一个鸡蛋。", "Mỗi sáng tôi ăn một quả trứng gà."),
    vocab("炸鸡", "zhájī", "gà rán", N, "孩子们都喜欢吃炸鸡。", "Bọn trẻ đều thích ăn gà rán."),
    vocab("香肠", "xiāngcháng", "xúc xích, lạp xưởng", N, "她买了两根香肠。", "Cô ấy mua hai cây xúc xích."),
    vocab("螃蟹", "pángxiè", "cua", N, "秋天的螃蟹很肥。", "Cua mùa thu rất béo."),
    vocab("鸭", "yā", "vịt", N, "湖里有一群鸭。", "Trong hồ có một đàn vịt."),
    vocab("烤鸭", "kǎoyā", "vịt quay", N, "北京烤鸭非常有名。", "Vịt quay Bắc Kinh rất nổi tiếng."),
    vocab("广州", "Guǎngzhōu", "Quảng Châu", PN, "广州是中国南方的大城市。", "Quảng Châu là một thành phố lớn ở miền Nam Trung Quốc."),
    vocab("南京", "Nánjīng", "Nam Kinh", PN, "南京有很多历史古迹。", "Nam Kinh có nhiều di tích lịch sử."),
    vocab("北京", "Běijīng", "Bắc Kinh", PN, "北京是中国的首都。", "Bắc Kinh là thủ đô của Trung Quốc."),
    vocab("成都", "Chéngdū", "Thành Đô", PN, "成都以美食和熊猫闻名。", "Thành Đô nổi tiếng với ẩm thực và gấu trúc."),
    vocab("河南", "Hénán", "Hà Nam", PN, "河南位于中国中部。", "Hà Nam nằm ở miền trung Trung Quốc."),
    vocab("四川", "Sìchuān", "Tứ Xuyên", PN, "四川菜常常又麻又辣。", "Món Tứ Xuyên thường vừa tê vừa cay."),
    vocab("邻居", "línjū", "hàng xóm", N, "邻居看见她买了很多菜。", "Người hàng xóm thấy cô ấy mua rất nhiều thức ăn."),
    vocab("客人", "kèrén", "khách", N, "今天晚上家里有客人。", "Tối nay nhà có khách."),
    vocab("做饭", "zuòfàn", "nấu cơm, nấu ăn", V, "她回家以后马上开始做饭。", "Sau khi về nhà cô ấy lập tức bắt đầu nấu ăn."),
    vocab("忽然", "hūrán", "bỗng nhiên", ADV, "忽然，门外传来了声音。", "Bỗng nhiên bên ngoài cửa vang lên tiếng động."),
    vocab("咚", "dōng", "thình, cộc", O, "门外传来“咚咚咚”的敲门声。", "Bên ngoài cửa vang lên tiếng gõ cộc cộc."),
    vocab("一顿饭", "yí dùn fàn", "một bữa cơm", P, "她要给男朋友做一顿丰盛的晚饭。", "Cô ấy muốn nấu cho bạn trai một bữa tối thịnh soạn."),
    vocab("吻", "wěn", "hôn", V, "她准备给男朋友一个甜甜的吻。", "Cô ấy chuẩn bị dành cho bạn trai một nụ hôn ngọt ngào."),
    vocab("而且", "érqiě", "hơn nữa, mà còn", ADV, "饭还没做好，而且时间还早。", "Cơm vẫn chưa nấu xong, hơn nữa thời gian còn sớm.")
  ]
});

window.HSK4_TOPICS.push({
  id: 10,
  title: "Quần áo và giặt giũ",
  chineseTitle: "衣服",
  description: "Toàn bộ từ vựng trong PDF: các loại quần áo, dịch vụ giặt và câu chuyện phơi đồ.",
  vocabulary: [
    vocab("衬衫", "chènshān", "áo sơ mi", N, "他今天穿了一件白衬衫。", "Hôm nay anh ấy mặc một chiếc áo sơ mi trắng."),
    vocab("袜子", "wàzi", "tất, vớ", N, "这双袜子是新买的。", "Đôi tất này mới mua."),
    vocab("长裤", "chángkù", "quần dài", N, "天气凉了，应该穿长裤。", "Trời mát rồi, nên mặc quần dài."),
    vocab("短裤", "duǎnkù", "quần đùi", N, "夏天穿短裤很凉快。", "Mùa hè mặc quần đùi rất mát."),
    vocab("裤衩", "kùchǎ", "quần lót", N, "这些裤衩要单独洗。", "Những chiếc quần lót này phải giặt riêng."),
    vocab("背心", "bèixīn", "áo ba lỗ", N, "他在家里穿着一件背心。", "Anh ấy mặc áo ba lỗ ở nhà."),
    vocab("裙子", "qúnzi", "váy", N, "这条红裙子很漂亮。", "Chiếc váy đỏ này rất đẹp."),
    vocab("手绢", "shǒujuàn", "khăn tay", N, "奶奶口袋里有一块手绢。", "Trong túi bà có một chiếc khăn tay."),
    vocab("毛衣", "máoyī", "áo len", N, "秋天我常常穿毛衣。", "Mùa thu tôi thường mặc áo len."),
    vocab("大衣", "dàyī", "áo khoác dài, áo bành tô", N, "他穿上大衣就出门了。", "Anh ấy mặc áo khoác dài rồi ra ngoài."),
    vocab("羽绒服", "yǔróngfú", "áo lông vũ, áo phao", N, "冬天穿羽绒服很暖和。", "Mùa đông mặc áo phao rất ấm."),
    vocab("西服", "xīfú", "com-lê, âu phục", N, "参加正式会议要穿西服。", "Tham dự cuộc họp trang trọng phải mặc âu phục."),
    vocab("中山装", "zhōngshānzhuāng", "áo Tôn Trung Sơn", N, "中山装是中国传统服装之一。", "Áo Tôn Trung Sơn là một trong những trang phục truyền thống của Trung Quốc."),
    vocab("旗袍", "qípáo", "sườn xám", N, "她穿旗袍的样子很优雅。", "Dáng cô ấy mặc sườn xám rất thanh lịch."),
    vocab("夹克衫", "jiákèshān", "áo khoác jacket", N, "春天穿夹克衫正合适。", "Mùa xuân mặc áo jacket rất phù hợp."),
    vocab("领带", "lǐngdài", "cà vạt", N, "穿西服时他会打领带。", "Khi mặc com-lê anh ấy sẽ thắt cà vạt."),
    vocab("洗衣机", "xǐyījī", "máy giặt", N, "我把脏衣服放进洗衣机。", "Tôi cho quần áo bẩn vào máy giặt."),
    vocab("洗衣店", "xǐyīdiàn", "tiệm giặt ủi", N, "这件大衣要送到洗衣店洗。", "Chiếc áo khoác này phải mang đến tiệm giặt ủi."),
    vocab("来历", "láilì", "nguồn gốc, lai lịch", N, "你知道旗袍的来历吗？", "Bạn có biết nguồn gốc của sườn xám không?"),
    vocab("脏", "zāng", "bẩn", A, "这些衣服穿了一个星期，很脏。", "Những bộ quần áo này đã mặc một tuần nên rất bẩn."),
    vocab("晾", "liàng", "phơi", V, "玛丽把洗好的衣服晾在绳子上。", "Mary phơi quần áo đã giặt lên dây."),
    vocab("湿", "shī", "ẩm, ướt", A, "这些湿衣服一会儿就会干。", "Những bộ quần áo ướt này lát nữa sẽ khô."),
    vocab("干", "gān", "khô", A, "太阳很好，衣服很快就干了。", "Nắng rất đẹp nên quần áo nhanh chóng khô."),
    vocab("绳子", "shéngzi", "dây thừng, sợi dây", N, "院子里有一根晾衣服的绳子。", "Trong sân có một sợi dây phơi quần áo.")
  ]
});

window.HSK4_TOPICS.push({
  id: 11,
  title: "Mắt, cơ thể và động tác",
  chineseTitle: "眼睛与身体部位",
  description: "Toàn bộ từ vựng trong PDF: bộ phận cơ thể, tư thế và câu chuyện về nỗi sợ.",
  vocabulary: [
    vocab("眼睛", "yǎnjing", "mắt", N, "她有一双明亮的眼睛。", "Cô ấy có một đôi mắt sáng."),
    vocab("耳朵", "ěrduo", "tai", N, "兔子的耳朵又长又大。", "Tai của con thỏ vừa dài vừa to."),
    vocab("眉毛", "méimao", "lông mày", N, "他的眉毛很浓。", "Lông mày của anh ấy rất rậm."),
    vocab("牙齿", "yáchǐ", "răng", N, "每天刷牙才能保护牙齿。", "Phải đánh răng mỗi ngày mới bảo vệ được răng."),
    vocab("鼻子", "bízi", "mũi", N, "他的鼻子有点儿红。", "Mũi của anh ấy hơi đỏ."),
    vocab("舌头", "shétou", "lưỡi", N, "吃饭时别咬到舌头。", "Khi ăn đừng cắn vào lưỡi."),
    vocab("嘴", "zuǐ", "miệng", N, "请张开嘴说“啊”。", "Hãy mở miệng nói “a”."),
    vocab("头发", "tóufa", "tóc", N, "她的头发又黑又长。", "Tóc của cô ấy vừa đen vừa dài."),
    vocab("站", "zhàn", "đứng", V, "老师站在教室前面。", "Giáo viên đứng phía trước lớp học."),
    vocab("坐", "zuò", "ngồi", V, "请坐在我的旁边。", "Hãy ngồi bên cạnh tôi."),
    vocab("蹲", "dūn", "ngồi xổm", V, "麦克蹲在地上学小狗叫。", "Mike ngồi xổm trên đất bắt chước tiếng chó sủa."),
    vocab("趴", "pā", "nằm sấp, úp người", V, "他喜欢趴在床上看书。", "Anh ấy thích nằm sấp trên giường đọc sách."),
    vocab("跪", "guì", "quỳ", V, "他跪在地上祈祷。", "Anh ấy quỳ trên mặt đất cầu nguyện."),
    vocab("躺", "tǎng", "nằm", V, "病人躺在床上休息。", "Bệnh nhân nằm trên giường nghỉ ngơi."),
    vocab("靠", "kào", "dựa, tựa", V, "她靠在墙上等朋友。", "Cô ấy tựa vào tường chờ bạn."),
    vocab("吊", "diào", "treo, đu", V, "猴子喜欢吊在树上。", "Khỉ thích đu trên cây."),
    vocab("祈祷", "qídǎo", "cầu nguyện", V, "人们正在安静地祈祷。", "Mọi người đang yên lặng cầu nguyện."),
    vocab("欺软怕硬", "qīruǎn pà yìng", "bắt nạt kẻ yếu, sợ kẻ mạnh", P, "那只小狗也是欺软怕硬的。", "Con chó nhỏ đó cũng bắt nạt kẻ yếu và sợ kẻ mạnh."),
    vocab("害怕", "hàipà", "sợ hãi", V, "玛丽看见小狗以后很害怕。", "Mary rất sợ sau khi nhìn thấy con chó."),
    vocab("凶", "xiōng", "dữ tợn", A, "那只狗看起来很凶。", "Con chó đó trông rất dữ."),
    vocab("吓", "xià", "dọa, làm sợ", V, "麦克的大叫把小狗吓了一跳。", "Tiếng hét của Mike làm con chó giật mình."),
    vocab("逃走", "táozǒu", "chạy trốn", V, "小狗吓得转身逃走了。", "Con chó sợ hãi quay người chạy mất."),
    vocab("看我的", "kàn wǒ de", "cứ để tôi, xem tôi đây", P, "别害怕，看我的！", "Đừng sợ, cứ xem tôi đây!"),
    vocab("可怕", "kěpà", "đáng sợ", A, "他的样子看起来真可怕。", "Dáng vẻ của anh ấy trông thật đáng sợ.")
  ]
});

window.HSK4_TOPICS.push({
  id: 12,
  title: "Hoạt động hằng ngày",
  chineseTitle: "日常活动",
  description: "Toàn bộ từ vựng trong PDF: đồ dùng vệ sinh, sinh hoạt hằng ngày và câu chuyện buổi sáng.",
  vocabulary: [
    vocab("牙刷", "yáshuā", "bàn chải đánh răng", N, "我每三个月换一次牙刷。", "Tôi thay bàn chải đánh răng ba tháng một lần."),
    vocab("牙膏", "yágāo", "kem đánh răng", N, "牙膏快用完了。", "Kem đánh răng sắp dùng hết rồi."),
    vocab("漱口杯", "shùkǒubēi", "cốc súc miệng", N, "牙刷放在漱口杯里。", "Bàn chải được đặt trong cốc súc miệng."),
    vocab("镜子", "jìngzi", "gương", N, "洗手间里有一面镜子。", "Trong nhà vệ sinh có một chiếc gương."),
    vocab("梳子", "shūzi", "cái lược", N, "她用梳子梳头发。", "Cô ấy dùng lược chải tóc."),
    vocab("毛巾", "máojīn", "khăn", N, "请用干净的毛巾擦脸。", "Hãy dùng khăn sạch lau mặt."),
    vocab("肥皂", "féizào", "xà phòng", N, "洗手时要用肥皂。", "Khi rửa tay phải dùng xà phòng."),
    vocab("吹风机", "chuīfēngjī", "máy sấy tóc", N, "她用吹风机吹干头发。", "Cô ấy dùng máy sấy làm khô tóc."),
    vocab("梳头", "shūtóu", "chải tóc", V, "她每天早上起床以后梳头。", "Mỗi sáng sau khi thức dậy cô ấy chải tóc."),
    vocab("照镜子", "zhào jìngzi", "soi gương", P, "出门以前他照了照镜子。", "Trước khi ra ngoài anh ấy soi gương."),
    vocab("上厕所", "shàng cèsuǒ", "đi vệ sinh", P, "小孩子说他想上厕所。", "Đứa trẻ nói rằng mình muốn đi vệ sinh."),
    vocab("小便", "xiǎobiàn", "đi tiểu", V, "医院要求病人检查小便。", "Bệnh viện yêu cầu bệnh nhân xét nghiệm nước tiểu."),
    vocab("大便", "dàbiàn", "đi đại tiện", V, "医生问孩子今天大便正常吗。", "Bác sĩ hỏi hôm nay việc đại tiện của đứa trẻ có bình thường không."),
    vocab("刷牙", "shuāyá", "đánh răng", V, "我每天早晚都刷牙。", "Tôi đánh răng mỗi sáng và tối."),
    vocab("洗脸", "xǐliǎn", "rửa mặt", V, "起床以后先刷牙洗脸。", "Sau khi thức dậy trước tiên đánh răng rửa mặt."),
    vocab("脱衣服", "tuō yīfu", "cởi quần áo", P, "洗澡以前要先脱衣服。", "Trước khi tắm phải cởi quần áo."),
    vocab("洗澡", "xǐzǎo", "tắm", V, "运动以后洗澡很舒服。", "Tắm sau khi vận động rất thoải mái."),
    vocab("穿衣服", "chuān yīfu", "mặc quần áo", P, "他闭着眼睛穿衣服。", "Anh ấy nhắm mắt mặc quần áo."),
    vocab("闹钟", "nàozhōng", "đồng hồ báo thức", N, "早上七点，闹钟响了。", "Bảy giờ sáng, đồng hồ báo thức reo."),
    vocab("卧室", "wòshì", "phòng ngủ", N, "他的卧室在二楼。", "Phòng ngủ của anh ấy ở tầng hai."),
    vocab("盥洗室", "guànxǐshì", "phòng rửa mặt, phòng vệ sinh", N, "他穿着拖鞋走进盥洗室。", "Anh ấy mang dép lê bước vào phòng vệ sinh."),
    vocab("响", "xiǎng", "reo, kêu, vang", V, "电话突然响了。", "Điện thoại đột nhiên reo."),
    vocab("水龙头", "shuǐlóngtóu", "vòi nước", N, "他打开水龙头洗脸。", "Anh ấy mở vòi nước rửa mặt."),
    vocab("脸盆", "liǎnpén", "chậu rửa mặt", N, "他在脸盆里放满了水。", "Anh ấy đổ đầy nước vào chậu rửa mặt."),
    vocab("鸡窝", "jīwō", "ổ gà", N, "他的头发乱得像鸡窝。", "Tóc anh ấy rối như một cái ổ gà."),
    vocab("头发像鸡窝", "tóufa xiàng jīwō", "tóc rối như ổ gà", P, "他刚起床，头发像鸡窝一样。", "Anh ấy vừa thức dậy, tóc rối như ổ gà."),
    vocab("睁眼", "zhēngyǎn", "mở mắt", V, "他太困了，眼睛都睁不开。", "Anh ấy buồn ngủ đến mức không mở nổi mắt."),
    vocab("迷糊", "míhu", "mơ màng, lơ mơ", A, "他迷迷糊糊地拿起了牙刷。", "Anh ấy lơ mơ cầm bàn chải lên."),
    vocab("挤", "jǐ", "bóp, nặn", V, "请把牙膏挤在牙刷上。", "Hãy bóp kem đánh răng lên bàn chải."),
    vocab("鞋油", "xiéyóu", "xi đánh giày", N, "他不小心把鞋油当成了牙膏。", "Anh ấy vô ý nhầm xi đánh giày thành kem đánh răng."),
    vocab("困", "kùn", "buồn ngủ", A, "我昨晚没睡好，现在很困。", "Tối qua tôi ngủ không ngon nên bây giờ rất buồn ngủ.")
  ]
});

window.HSK4_TOPICS.push({
  id: 13,
  title: "Công viên và nhiếp ảnh",
  chineseTitle: "公园与摄影",
  description: "Toàn bộ từ vựng trong PDF: thiết bị chụp ảnh, cảnh vật trong công viên và câu chuyện chụp ảnh.",
  vocabulary: [
    vocab("照相机", "zhàoxiàngjī", "máy ảnh", N, "他拿着照相机在公园里拍照。", "Anh ấy cầm máy ảnh chụp hình trong công viên."),
    vocab("镜头", "jìngtóu", "ống kính", N, "拍照以前请先擦干净镜头。", "Trước khi chụp hãy lau sạch ống kính."),
    vocab("快门", "kuàimén", "nút chụp, màn trập", N, "他对着玛丽按下了快门。", "Anh ấy hướng máy về Mary và bấm nút chụp."),
    vocab("取景框", "qǔjǐngkuāng", "khung ngắm", N, "我从取景框里看到了瀑布。", "Tôi nhìn thấy thác nước qua khung ngắm."),
    vocab("闪光灯", "shǎnguāngdēng", "đèn flash", N, "光线太暗，请打开闪光灯。", "Ánh sáng quá tối, hãy bật đèn flash."),
    vocab("胶卷", "jiāojuǎn", "cuộn phim", N, "这种老照相机需要装胶卷。", "Loại máy ảnh cũ này cần lắp cuộn phim."),
    vocab("电池", "diànchí", "pin", N, "照相机的电池快没电了。", "Pin máy ảnh sắp hết."),
    vocab("底片", "dǐpiàn", "phim âm bản", N, "这些底片保存得很好。", "Những tấm phim âm bản này được bảo quản rất tốt."),
    vocab("相片", "xiàngpiàn", "ảnh, tấm ảnh", N, "我们一起看刚洗出来的相片。", "Chúng tôi cùng xem những bức ảnh vừa được rửa."),
    vocab("花儿", "huār", "hoa", N, "公园里的花儿开得很漂亮。", "Hoa trong công viên nở rất đẹp."),
    vocab("蝴蝶", "húdié", "con bướm", N, "一只蝴蝶在花丛中飞来飞去。", "Một con bướm bay qua bay lại giữa khóm hoa."),
    vocab("草", "cǎo", "cỏ", N, "小羊正在草地上吃草。", "Chú cừu đang ăn cỏ trên bãi."),
    vocab("树", "shù", "cây", N, "湖边有几棵大树。", "Bên hồ có vài cây lớn."),
    vocab("蜻蜓", "qīngtíng", "chuồn chuồn", N, "夏天常常能在水边看到蜻蜓。", "Mùa hè thường thấy chuồn chuồn gần mặt nước."),
    vocab("假山石", "jiǎshānshí", "đá hòn non bộ", N, "孩子们在公园的假山石旁边玩儿。", "Bọn trẻ chơi cạnh hòn non bộ trong công viên."),
    vocab("亭子", "tíngzi", "đình, chòi nghỉ", N, "累了以后我们在亭子里休息。", "Mệt rồi chúng tôi nghỉ trong đình."),
    vocab("瀑布", "pùbù", "thác nước", N, "山里的瀑布非常壮观。", "Thác nước trong núi rất hùng vĩ."),
    vocab("草坪", "cǎopíng", "bãi cỏ", N, "请不要在草坪上乱扔垃圾。", "Xin đừng vứt rác bừa bãi trên bãi cỏ."),
    vocab("树林", "shùlín", "rừng cây, khu rừng nhỏ", N, "他们在小树林里散步。", "Họ đi dạo trong khu rừng nhỏ."),
    vocab("森林", "sēnlín", "rừng", N, "这片森林里生活着很多动物。", "Nhiều động vật sống trong khu rừng này."),
    vocab("飘", "piāo", "bay, trôi, phấp phới", V, "天上飘着几朵白云。", "Trên trời có vài đám mây trắng trôi."),
    vocab("恋人", "liànrén", "người yêu, đôi tình nhân", N, "湖边坐着一对恋人。", "Bên hồ có một đôi tình nhân đang ngồi."),
    vocab("游艇", "yóutǐng", "du thuyền", N, "湖上有一艘白色的游艇。", "Trên hồ có một chiếc du thuyền màu trắng."),
    vocab("划", "huá", "chèo", V, "他们正在湖里划游艇。", "Họ đang chèo du thuyền trên hồ."),
    vocab("留念", "liúniàn", "lưu niệm, làm kỷ niệm", V, "我们在公园里拍几张照片留念。", "Chúng tôi chụp vài tấm ảnh trong công viên làm kỷ niệm."),
    vocab("石头", "shítou", "đá, hòn đá", N, "麦克站在一块大石头上。", "Mike đứng trên một tảng đá lớn."),
    vocab("倒立", "dàolì", "trồng cây chuối, đứng bằng tay", V, "他在石头上来了个倒立。", "Anh ấy thực hiện một động tác trồng cây chuối trên tảng đá."),
    vocab("洗印", "xǐyìn", "rửa và in ảnh", V, "相片很快就洗印出来了。", "Những bức ảnh nhanh chóng được rửa ra."),
    vocab("放大", "fàngdà", "phóng to", V, "这张相片洗印以后还放大了。", "Bức ảnh này sau khi rửa còn được phóng to."),
    vocab("大力士", "dàlìshì", "lực sĩ, người rất khỏe", N, "相片里的麦克看起来像个大力士。", "Mike trong ảnh trông giống một lực sĩ.")
  ]
});
